[project]
name = 'token-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.FanToken]
path = 'contracts/FanToken.clar'
clarity_version = 2
epoch = 2.4

[contracts.TokenGatedCommunity]
path = 'contracts/TokenGatedCommunity.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
